//#line 2 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the localization3d_node package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __localization3d_node__LOCALIZATION3DCONFIG_H__
#define __localization3d_node__LOCALIZATION3DCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace localization3d_node
{
  class Localization3dConfigStatics;
  
  class Localization3dConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(Localization3dConfig &config, const Localization3dConfig &max, const Localization3dConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const Localization3dConfig &config1, const Localization3dConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, Localization3dConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const Localization3dConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, Localization3dConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const Localization3dConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T Localization3dConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (Localization3dConfig::* field);

      virtual void clamp(Localization3dConfig &config, const Localization3dConfig &max, const Localization3dConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const Localization3dConfig &config1, const Localization3dConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, Localization3dConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const Localization3dConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, Localization3dConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const Localization3dConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 43 "../cfg/localization3d_alg_config.cfg"
      int num_particles;
//#line 44 "../cfg/localization3d_alg_config.cfg"
      double initX;
//#line 45 "../cfg/localization3d_alg_config.cfg"
      double initY;
//#line 46 "../cfg/localization3d_alg_config.cfg"
      double initH;
//#line 47 "../cfg/localization3d_alg_config.cfg"
      std::string mapFile;
//#line 48 "../cfg/localization3d_alg_config.cfg"
      std::string floorGridFile;
//#line 138 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("Localization3dConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const Localization3dConfig &__max__ = __getMax__();
      const Localization3dConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const Localization3dConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const Localization3dConfig &__getDefault__();
    static const Localization3dConfig &__getMax__();
    static const Localization3dConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const Localization3dConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void Localization3dConfig::ParamDescription<std::string>::clamp(Localization3dConfig &config, const Localization3dConfig &max, const Localization3dConfig &min) const
  {
    return;
  }

  class Localization3dConfigStatics
  {
    friend class Localization3dConfig;
    
    Localization3dConfigStatics()
    {
//#line 43 "../cfg/localization3d_alg_config.cfg"
      __min__.num_particles = 10;
//#line 43 "../cfg/localization3d_alg_config.cfg"
      __max__.num_particles = 10000;
//#line 43 "../cfg/localization3d_alg_config.cfg"
      __default__.num_particles = 30;
//#line 43 "../cfg/localization3d_alg_config.cfg"
      __param_descriptions__.push_back(Localization3dConfig::AbstractParamDescriptionConstPtr(new Localization3dConfig::ParamDescription<int>("num_particles", "int", -1, "NumberOfParticles", "", &Localization3dConfig::num_particles)));
//#line 44 "../cfg/localization3d_alg_config.cfg"
      __min__.initX = -1000.0;
//#line 44 "../cfg/localization3d_alg_config.cfg"
      __max__.initX = 1000.0;
//#line 44 "../cfg/localization3d_alg_config.cfg"
      __default__.initX = 0.0;
//#line 44 "../cfg/localization3d_alg_config.cfg"
      __param_descriptions__.push_back(Localization3dConfig::AbstractParamDescriptionConstPtr(new Localization3dConfig::ParamDescription<double>("initX", "double", -1, "intial X", "", &Localization3dConfig::initX)));
//#line 45 "../cfg/localization3d_alg_config.cfg"
      __min__.initY = -1000.0;
//#line 45 "../cfg/localization3d_alg_config.cfg"
      __max__.initY = 1000.0;
//#line 45 "../cfg/localization3d_alg_config.cfg"
      __default__.initY = 0.0;
//#line 45 "../cfg/localization3d_alg_config.cfg"
      __param_descriptions__.push_back(Localization3dConfig::AbstractParamDescriptionConstPtr(new Localization3dConfig::ParamDescription<double>("initY", "double", -1, "intial Y", "", &Localization3dConfig::initY)));
//#line 46 "../cfg/localization3d_alg_config.cfg"
      __min__.initH = -3.1416;
//#line 46 "../cfg/localization3d_alg_config.cfg"
      __max__.initH = 3.1416;
//#line 46 "../cfg/localization3d_alg_config.cfg"
      __default__.initH = 0.0;
//#line 46 "../cfg/localization3d_alg_config.cfg"
      __param_descriptions__.push_back(Localization3dConfig::AbstractParamDescriptionConstPtr(new Localization3dConfig::ParamDescription<double>("initH", "double", -1, "intial Heading", "", &Localization3dConfig::initH)));
//#line 47 "../cfg/localization3d_alg_config.cfg"
      __min__.mapFile = "";
//#line 47 "../cfg/localization3d_alg_config.cfg"
      __max__.mapFile = "";
//#line 47 "../cfg/localization3d_alg_config.cfg"
      __default__.mapFile = "";
//#line 47 "../cfg/localization3d_alg_config.cfg"
      __param_descriptions__.push_back(Localization3dConfig::AbstractParamDescriptionConstPtr(new Localization3dConfig::ParamDescription<std::string>("mapFile", "str", -1, "OBJ file with the 3D_model", "", &Localization3dConfig::mapFile)));
//#line 48 "../cfg/localization3d_alg_config.cfg"
      __min__.floorGridFile = "";
//#line 48 "../cfg/localization3d_alg_config.cfg"
      __max__.floorGridFile = "";
//#line 48 "../cfg/localization3d_alg_config.cfg"
      __default__.floorGridFile = "";
//#line 48 "../cfg/localization3d_alg_config.cfg"
      __param_descriptions__.push_back(Localization3dConfig::AbstractParamDescriptionConstPtr(new Localization3dConfig::ParamDescription<std::string>("floorGridFile", "str", -1, "TXT file with the elevation grid", "", &Localization3dConfig::floorGridFile)));
//#line 239 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<Localization3dConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<Localization3dConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    Localization3dConfig __max__;
    Localization3dConfig __min__;
    Localization3dConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const Localization3dConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static Localization3dConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &Localization3dConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const Localization3dConfig &Localization3dConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const Localization3dConfig &Localization3dConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const Localization3dConfig &Localization3dConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<Localization3dConfig::AbstractParamDescriptionConstPtr> &Localization3dConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const Localization3dConfigStatics *Localization3dConfig::__get_statics__()
  {
    const static Localization3dConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = Localization3dConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __LOCALIZATION3DRECONFIGURATOR_H__
